### ISSUE TITLE
when ending an experiment, mention that you can always resume it

### ISSUE THREAD

**Issue by nsfmc** [kamens/gae_bingo#1]
currently, when ending an experiment, you're faced with this js alert:

> Are you sure you want to end this experiment and choose alternative #1?
> **_If you have multiple experiments running with the same experiment name, you will end and choose this alternative for all of them.**_

it's not clear that you can restart the experiment from the text, but you can, and maybe just noting something like "it's ok, you can go resume it again if you want to!" might make the decision less stressful.

it's nice though that you can end and resume an experiment, though, it makes testing each condition easier.

**Comment by kamens** [comment]
@nsfmc Good advice, will do that.

**Comment by kamens** [comment]
done
