### ISSUE TITLE
Current status of GAE Bingo

### ISSUE THREAD

**Issue by kevinburke** [kamens/gae_bingo#7]
Hi Ben - 
    I saw the last commit to this repo was on November 1. Is this still in use at KA? Is this repo still in active development? What have you learned from using it?

Kevin

**Comment by kamens** [comment]
Hey Kevin -- yup! Still in heavy use (heavier than ever) at KA. One of our
latest uses:
http://david-hu.com/2011/11/02/how-khan-academy-is-using-machine-learning-to-assess-student-mastery.html

We've got some tweaks in our version that haven't made it to the public
github repo yet, but I hope to bring 'em back one day. This repo will still
work just fine as it stands -- if not, lemme know.

On Sat, Feb 4, 2012 at 3:55 PM, Kevin Burke <
reply@reply.github.com

**Comment by kevinburke** [comment]
Awesome.
