### ISSUE TITLE
exists() references methods that are not imported

### ISSUE THREAD

**Issue by kevinburke** [kamens/gae_bingo#8]
In models.py on line 76:

```
@staticmethod
def exists(name):
    return cache.exists(Experiment.key_for_name(name))
```

I believe you want a "import cache" line at the beginning of the file. In addition the `import logging` line at the top of models.py is not used.

**Comment by kamens** [comment]
Are you using this function? I'm partially tempted to remove it.

On Sat, Feb 4, 2012 at 11:38 PM, Kevin Burke <
reply@reply.github.com

**Comment by kevinburke** [comment]
No I'm not. My editor just red-flagged it and I thought I'd report it.

## 

Kevin Burke | Twilio
phone: 925.271.7005 | kev.inburke.com

On Wed, Feb 8, 2012 at 11:45 AM, Ben Kamens <
reply@reply.github.com
